#!/usr/bin/lua

--add prefix to hostname, if non existent
local site = require 'gluon.site'
local uci = require('simple-uci').cursor()
local pretty_hostname = require 'pretty_hostname'

local prefix = site.hostname_prefix()
local hostn = pretty_hostname.get(uci)
local hostn_preifix = hostn:sub(1,prefix:len())
 
local f=io.open('/root/tom.log','w')
 f:write(string.format("prefix: '%s'\n",prefix))
 f:write(string.format("hostname '%s' \n",hostname)) 
 f:close()

if (prefix:upper()~=hostn_preifix:upper()) then  
  local hostn_new = prefix .. hostn  
  uci:set('system', '@system[0]', 'hostname', hostn_new)
  uci:save('system')  
  uci:commit('system')    
  local f2=io.open('/root/tom2.log','w')   
   f2:write(string.format("newhostname '%s' \n",hostn_new))
   f2:close()
end
