#!/usr/bin/lua

--add prefix to hostname, if non existent
local site = require 'gluon.site'
local uci = require('simple-uci').cursor()

local prefix = site.hostname_prefix()
local hostn = uci:get('system', '@system[0]', 'hostname')
local hostn_preifix = hostn:sub(1,prefix:len())

io.stderr:write(string.format("prefix: '%s' hostname '%s' \n",prefix,hostname))

if (prefix:upper()~=hostn_preifix:upper()) then  
  local hostn_new = prefix .. hostn  
  uci:set('system', '@system[0]', 'hostname', hostn_new)
  uci:save('system')  
  uci:commit('system')  
  io.stderr:write(string.format("newhostname '%s' \n",hostn_new))
end
